# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'endWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import time

from PyQt5 import QtCore, QtGui, QtWidgets


class endWindowClass(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(180, 330, 281, 28))
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 150, 280, 30))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(130, 240, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(170, 35, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(170, 70, 381, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(170, 90, 500, 16))
        self.label_4.setObjectName("label_4")
        self.label_2.setHidden(True)
        self.label_3.setHidden(True)
        self.label_4.setHidden(True)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.label_5.setGeometry(QtCore.QRect(280, 210, 280, 30))
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setObjectName("pushbutton_3")
        self.pushButton_3.setGeometry(QtCore.QRect(180, 380, 280, 30))
        self.pushButton_3.setText("Try Once Again")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "End test"))
        self.pushButton_2.setText(_translate("Form", "Show spoiler"))
        self.label.setText(_translate("Form", "Conguratulations! You have finished!"))
        self.label_2.setText(_translate("Form", "SPOILER:"))
        self.label_3.setText(_translate("Form", "You took part in Dr. Asch experiment"))
        self.label_4.setText(_translate("Form", "<a href='https://en.wikipedia.org/wiki/Solomon_Asch'>More "
                                                "information you can find here: "
                                                "https://en.wikipedia.org/wiki/Solomon_Asch </a> "))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = endWindowClass()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
