# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class formWindowClass(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 40, 80, 40))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(120, 50, 110, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setText("John")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 90, 110, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setText("Doe")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 80, 40))
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 130, 110, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setText("19")
        self.onlyInt = QtGui.QIntValidator(18, 99)
        self.lineEdit_3.setValidator(self.onlyInt)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 80, 20))
        self.label_3.setObjectName("label_3")
        self.combobox = QtWidgets.QComboBox(Form)
        self.combobox.setGeometry(QtCore.QRect(120,210,110,20))
        self.combobox.addItem("Male")
        self.combobox.addItem("Female")
        self.combobox.addItem("Other")
        self.combobox_2 = QtWidgets.QComboBox(Form)
        self.combobox_2.setGeometry(QtCore.QRect(120, 170, 200, 20))
        self.combobox_2.setObjectName("combobox_2")
        self.combobox_2.addItem("Primary education")
        self.combobox_2.addItem("Lower secondary education")
        self.combobox_2.addItem("Upper secondary education")
        self.combobox_2.addItem("Post-secondary non-tertiary education")
        self.combobox_2.addItem("Short-cycle tertiary education")
        self.combobox_2.addItem("Bachelor's or equivalent")
        self.combobox_2.addItem("Master's or equivalent")
        self.combobox_2.addItem("Doctoral or equivalent")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(40, 160, 80, 40))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(40, 200, 80, 40))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(40, 300, 80, 30))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setEnabled(False)
        self.lineEdit_3.setValidator(QtGui.QIntValidator())
        self.lineEdit_3.setMaxLength(2)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 260, 80, 30))
        self.pushButton_2.setObjectName("checkbox")

        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.label_6.setGeometry(QtCore.QRect(205, 130, 400, 40))
        self.label_6.setStyleSheet("color: red; font: bold 14px;")
        self.label_6.setHidden(True)
        self.label_6.setAlignment(Qt.AlignHCenter|Qt.AlignTop)

        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_6")
        self.label_7.setGeometry(QtCore.QRect(40, 350, 150, 50))
        self.label_7.setStyleSheet("color: green;"
                                   "font: bold 14px;"
                                   "border-style: outset;"
                                   "border-radius: 10px;"
                                   "border-color: green;"
                                   "border-width: 2px")
        self.label_7.setHidden(True)

        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.label_8.setGeometry(QtCore.QRect(250, 40, 150, 40))
        self.label_8.setStyleSheet("color: red; font: bold 14px;")
        self.label_8.setHidden(True)

        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.label_9.setGeometry(QtCore.QRect(250, 80, 150, 40))
        self.label_9.setStyleSheet("color: red; font: bold 14px;")
        self.label_9.setHidden(True)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "First name:"))
        self.label_2.setText(_translate("Form", "Last name:"))
        self.label_3.setText(_translate("Form", "Age:"))
        self.label_4.setText(_translate("Form", "Education level:"))
        self.label_5.setText(_translate("Form", "Sex:"))
        self.label_6.setText(_translate("Form", "age incorrect, must be 18-99 and not empty!"))
        self.label_7.setText(_translate("Form", "Success!"))
        self.label_8.setText(_translate("Form", "First name is empty!"))
        self.label_9.setText(_translate("Form", "Last name is empty!"))

        self.pushButton.setText(_translate("Form", "Submit"))
        self.pushButton_2.setText((_translate("Form", "Verify data")))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = formWindowClass()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
